import "./globals.css";

import { Inter } from "next/font/google";
const inter = Inter({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <FloatingNav />
        {children}
      </body>
    </html>
  );
}

function FloatingNav() {
  return (
    <>
      <a href="/">
        <div className={`${inter.className} absolute w-12 h-10 hover:w-fit bg-white shadow-md bottom-10 left-10 flex items-center px-3 group`}>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>

          <span className="hidden group-hover:block text-sm ml-2"> Back to Home</span>
        </div>
      </a>
    </>
  );
}
